### PR TITLE
Add other initiative websites, minor typo corrections

### PR DESCRIPTION
**Pull request by tjcrone**

### CODE REVIEW

**Comment by rabernat** [comment]
This all looks good. Want me to merge right away, or will you make more commits?

**Comment by tjcrone** [comment]
Well, the sensor systems page needs much more work, but I am probably done for the day, and tomorrow and maybe Friday as well. Let's go ahead and merge these changesets. If something I did broke the look, I will commit a fix tonight, but otherwise, let's push in the changes and let them meet the others.

**Comment by tjcrone** [comment]
When I have time to get back to this, I will run my own mirror of this entire site so that I can see how the template files deal with my changes.

**Comment by rabernat** [comment]
It's easy to build and serve the site on your local computer. You just need jekyll installed.
https://jekyllrb.com/docs/quickstart/

**Comment by tjcrone** [comment]
Do you have a mirror aside from the LDEO site so that I can see the changes now that you have merged?

**Comment by rabernat** [comment]
No sorry, I don't have any other mirror that is published on the web.

I just rebuilt with your changes and copied up to the site.

**Comment by tjcrone** [comment]
Okay thanks. It looks great. The links work. The Sensor System page is a touch messed up, but not that bad, and it is very not done anyway, so I am not going to fix it today. Unless you want me to. Please let me know. Otherwise, have a nice Thanksgiving, and great job getting this site started. This is a great development and puts us in a great position.

**Pull request merged**
